const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Plugins.Tilemap,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Behaviors.Pin,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.choose
	];
};
self.C3_JsPropNameTable = [
	{GameTitle: 0},
	{PlayButton: 0},
	{PlayText: 0},
	{EnemyHP: 0},
	{Enemy: 0},
	{Tilemap: 0},
	{Door: 0},
	{CanAttack: 0},
	{DropKnife: 0},
	{DropGlock: 0},
	{Platform: 0},
	{Player: 0},
	{Solid: 0},
	{Pin: 0},
	{Punch: 0},
	{Keyboard: 0},
	{Audio: 0},
	{Knife: 0},
	{KnifeItem: 0},
	{ItemHUD: 0},
	{Glock: 0},
	{GlockItem: 0},
	{Box: 0},
	{Bullet: 0},
	{GlockBullet: 0},
	{Player2: 0},
	{Mouse: 0},
	{Item: 0}
];

self.InstanceType = {
	GameTitle: class extends self.ITextInstance {},
	PlayButton: class extends self.ISpriteInstance {},
	PlayText: class extends self.ITextInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Door: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Solid: class extends self.ISpriteInstance {},
	Punch: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Knife: class extends self.ISpriteInstance {},
	KnifeItem: class extends self.ISpriteInstance {},
	ItemHUD: class extends self.ISpriteInstance {},
	Glock: class extends self.ISpriteInstance {},
	GlockItem: class extends self.ISpriteInstance {},
	Box: class extends self.ISpriteInstance {},
	GlockBullet: class extends self.ISpriteInstance {},
	Player2: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {}
}